services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzUITreeMenuBundle\Controller\:
        resource: "../../Controller/*"
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]
