edgar.uitreemenu.init:
    path: /init/{locationId}
    methods: [ "GET" ]
    defaults:
        _controller: 'EdgarEzUITreeMenuBundle:UITreeMenu:init'

edgar.uitreemenu.children:
    path: /children/{locationId}/{offset}
    methods: [ "GET" ]
    defaults:
        _controller: 'EdgarEzUITreeMenuBundle:UITreeMenu:children'
